// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcPLRy3JpW3L_lWyGxywiVtFVxGubsXrg',
    appId: '1:826586943522:web:61df38295b127394007a7b',
    messagingSenderId: '826586943522',
    projectId: 'test-project-2c656',
    authDomain: 'test-project-2c656.firebaseapp.com',
    storageBucket: 'test-project-2c656.appspot.com',
    measurementId: 'G-BH413Y8R64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAta7ejSWuZqg8h7YX8u-bOdgU_P52YHvI',
    appId: '1:826586943522:android:695e4b43a41c21c8007a7b',
    messagingSenderId: '826586943522',
    projectId: 'test-project-2c656',
    storageBucket: 'test-project-2c656.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4RXL-FhNlI2dvxXafzP164X5aB4LiOIQ',
    appId: '1:826586943522:ios:1530333bdd7e2c1f007a7b',
    messagingSenderId: '826586943522',
    projectId: 'test-project-2c656',
    storageBucket: 'test-project-2c656.appspot.com',
    iosBundleId: 'com.example.flutterPracticeProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4RXL-FhNlI2dvxXafzP164X5aB4LiOIQ',
    appId: '1:826586943522:ios:1530333bdd7e2c1f007a7b',
    messagingSenderId: '826586943522',
    projectId: 'test-project-2c656',
    storageBucket: 'test-project-2c656.appspot.com',
    iosBundleId: 'com.example.flutterPracticeProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcPLRy3JpW3L_lWyGxywiVtFVxGubsXrg',
    appId: '1:826586943522:web:8b1b7c5da0b6b583007a7b',
    messagingSenderId: '826586943522',
    projectId: 'test-project-2c656',
    authDomain: 'test-project-2c656.firebaseapp.com',
    storageBucket: 'test-project-2c656.appspot.com',
    measurementId: 'G-ZRQJCRB2CH',
  );

}