// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkeYRKyC4aBizJ8R2-QLPGAP2Ai-sRxqM',
    appId: '1:1032047036746:web:c568edd83e1d33134f99b3',
    messagingSenderId: '1032047036746',
    projectId: 'test-project-1fb19',
    authDomain: 'test-project-1fb19.firebaseapp.com',
    storageBucket: 'test-project-1fb19.appspot.com',
    measurementId: 'G-F7C7EKWXST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD71iTkfB5gjQ51kzoUAH2Lm9ll83DbjD0',
    appId: '1:1032047036746:android:e7eb09f6a7e135494f99b3',
    messagingSenderId: '1032047036746',
    projectId: 'test-project-1fb19',
    storageBucket: 'test-project-1fb19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq_zJZO08PAYSJJ9QC-OUF2O2BpUr9st0',
    appId: '1:1032047036746:ios:99e7b3f6ef09c2b54f99b3',
    messagingSenderId: '1032047036746',
    projectId: 'test-project-1fb19',
    storageBucket: 'test-project-1fb19.appspot.com',
    iosBundleId: 'com.example.flutterPracticeProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq_zJZO08PAYSJJ9QC-OUF2O2BpUr9st0',
    appId: '1:1032047036746:ios:99e7b3f6ef09c2b54f99b3',
    messagingSenderId: '1032047036746',
    projectId: 'test-project-1fb19',
    storageBucket: 'test-project-1fb19.appspot.com',
    iosBundleId: 'com.example.flutterPracticeProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkeYRKyC4aBizJ8R2-QLPGAP2Ai-sRxqM',
    appId: '1:1032047036746:web:106453cced694d194f99b3',
    messagingSenderId: '1032047036746',
    projectId: 'test-project-1fb19',
    authDomain: 'test-project-1fb19.firebaseapp.com',
    storageBucket: 'test-project-1fb19.appspot.com',
    measurementId: 'G-7F3MQ5B8CX',
  );
}
